### ISSUE TITLE
crash on update in lantz-qtdemo testpanel

### ISSUE THREAD

**Issue by Bruyant** [lantzproject/lantz#3]
Hi,

after  

> lantz-qtdemo testpanel 

and clicking on update I get a crash

```
Traceback (most recent call last):
  File "/Users/nicolasbruyant/anaconda3/envs/lantz2/lib/python3.6/site-packages/lantz/qt/widgets/testgui.py", line 59, in <lambda>
    update.clicked.connect(lambda x: target.update(self.widgets_values_as_dict()))
  File "/Users/nicolasbruyant/anaconda3/envs/lantz2/lib/python3.6/site-packages/lantz/qt/widgets/testgui.py", line 163, in widgets_values_as_dict
    for widget in self.writable_widgets}
  File "/Users/nicolasbruyant/anaconda3/envs/lantz2/lib/python3.6/site-packages/lantz/qt/widgets/testgui.py", line 163, in <dictcomp>
    for widget in self.writable_widgets}
AttributeError: 'LabeledFeatWidget' object has no attribute 'feat'
Abort trap: 6
```

Note: there is a typo in the doc we I needed to run  "lantz-qtdemo testpanel" and not "lantz qtdemo testpanel" as stated on the doc

**Comment by hgrecco** [comment]
Yes, the update command is not working yet. But everything else in the test panel should work.

Regarding the cli `lantz qtdemo testpanel` is correct (and the recommended way to do it). The `lantz` cli automatically queries the subpackages for subcommands. The option with a hyphen is created as an alternative (in the same git used to do it).
